name: berehearsal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+1
  url_launcher: ^6.3.0
  settings_ui: ^2.0.2
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.1
  screen_protector: ^1.4.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/images/debug/undefined_image.png


  fonts:
    - family: NotoSansJP-ExtraBold
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraBold.ttf
    - family: NotoSansJP-SemiBold
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-SemiBold.ttf
    - family: NotoSansJP-Bold
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.ttf
    - family: NotoSansJP-Medium
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.ttf
    - family: NotoSansJP-Regular
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.ttf
    - family: NotoSansJP-SemiBold
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-SemiBold.ttf
    - family: NotoSansJP-Thin
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Thin.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Inter/Inter_Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter/Inter_ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter_ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter_ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter_Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/Inter_Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter_LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter_Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter_Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter_ThinItalic.ttf
          weight: 100
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/app_icon_square.png"